const COLORS = {
	AERO_ORANGE: "#FDAF1D" /* IS NOT EXACT THE SAME AS AEROLABS ONE */,
	YELLOW_COIN: "#FDD13D",
	MAIN_BLUE: "#0AD4FA",
	DARK_BLUE: "#12BBFF",
};

const MEDIA_SIZES = {
	MOBILE: "320px",
	TABLET: "768px",
	DESKTOP: "1024px",
	LARGE_DESKTOP: "1440px",
};

export { COLORS, MEDIA_SIZES };
